### ISSUE TITLE
feat: specify `KO_DOCKER_REPO` in `.ko.yaml`

### ISSUE THREAD

**Issue by miguelvr** [ko-build/ko#1228]
## Description

In order to facilitate local reproducible builds for developers, it would be a nicer UX if we could specify a default image repo, globally or per image, in `.ko.yaml`. This can be useful in scenarios like monorepos and generally reduces the surface for user error.

## Proposal

For images with different repos:
```yaml
imageRepo: ghcr.io/org/repo1

- id: foo
  dir: ./foo
  main: . 
- id: bar
  dir: ./bar
  main: . 
  imageRepo: ghcr.io/org/repo2
```

`foo` → pushed to `ghcr.io/org/repo/foo`
`bar` → pushed to `ghcr.io/org/repo2/bar`

> [!NOTE]
> To keep backward compatibility, `KO_DOCKER_REPO` would overwrite any of these options.
