### ISSUE TITLE
Question: set argv parameters for the built binaries?

### ISSUE THREAD

**Issue by idc77** [ko-build/ko#1274]
I have this binary that uses cobra (spf13) and has various arguments, like
--db= --conn= --usereverseproxy --trustedproxies
etc

I used to write simple build and publish bash scripts and have now set up a docker registry and am, at home for now, experimenting with k8s (1cp 1w microk8s).

Searching the web I found ko and I'm trying to make sense of it all.

```bash
#!/bin/bash
ko login domain -u user -p password
KO_DOCKER_REPO=domain/user/project ko build
```

I have not been able to run this uploaded to the registry thing yet (trying to find out how)
but I'm sure that I'll need some argv set.

How?

**Comment by idc77** [comment]
Well that was quite the noob question

```
apiVersion: v1
kind: Pod
metadata:
  name: iloveu-backend
  labels:
    role: backend
  namespace: iloveu
spec:
    containers:
    - name: backend
      image: registry.domain.tld/iloveu/backend/iloveu-3e46d27deb2b924b7bad8de8eeab40cd
      command: [iloveu]
      args: ["restful", "--bp=false", "--debug=false", "--addr=tcp::7777", "--conn=mongodb://user:pass@mongodb.mongodb.svc.cluster.local:27017/iloveu"]
      ports:
        - containerPort: 7777
    imagePullSecrets:
      - name: registrycredentials
    restartPolicy: Never
```

The mountain is steep, but I'll get there
