### ISSUE TITLE
upper-case letters in Github username cause build to fail

### ISSUE THREAD

**Issue by VincentSchmid** [ko-build/ko#1400]
My username on gihtub has upper and lowecase letters. So this should be valid or be handled within ko-build.

This is my Pipeline (default from the README:

```
name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: ko build
```

And the error I get is:
```
Run ko build
Error: error creating publisher: failed to parse "ghcr.io/VincentSchmid/whisper-server" as repository: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: VincentSchmid/whisper-server
```
