### ISSUE TITLE
FR: configure platforms in .ko.yaml

### ISSUE THREAD

**Issue by n3wscott** [ko-build/ko#521]
In the new fancy world of Mac M1 Apple silicon, I run into the issue of my dev loop causing me grief because when I target an arch that is not arm64 (like my normal k8s clusters).

What if ko could probe the target cluster and figure out the `--platform` flag?

**edit(jason):** see https://github.com/ko-build/ko/issues/521#issuecomment-1325676486

**Comment by halvards** [comment]
It's not quite a cluster probe, but if you can identify the node arch by the kubecontext name, then you could use Skaffold's [`ko` builder](https://skaffold.dev/docs/pipeline-stages/builders/ko/) and switch platforms using [profiles](https://skaffold.dev/docs/environment/profiles/).

Here's an example config:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: ko://example.com/org/app
    ko:
      platforms:
      - linux/arm64
profiles:
- name: not-an-arm64-cluster
  activation:
  - kubeContext: '!minikube'
  patches:
  - op: replace
    path: /build/artifacts/0/ko/platforms/0
    value: linux/amd64
```

In this example, the `not-an-arm64-cluster` profile kicks in if the current kubecontext name is _not_ `minikube`.

You can be more clever with the `activation` section if needed, by using regex matching, environment variables, or Skaffold sub-commands (e.g., activate for [`skaffold build`](https://skaffold.dev/docs/references/cli/#skaffold-build) but not for [`skaffold dev`](https://skaffold.dev/docs/references/cli/#skaffold-dev), etc).
