### ISSUE TITLE
Add image labels to .ko.yaml config

### ISSUE THREAD

**Issue by ericsmalling** [ko-build/ko#825]
I would like to be able to configure image labels/annotations from the the .ko.yaml file so that oranizations with standardized label requirements can specify them there instead of only via the CLI `--image-label` flag.

Additionally, the values for these labels should be able to be interpolated/expanded at run time via environment variables.

Example config:
```yaml
...
image-labels:
  - org: mycorp-devrel
  - ci-build: {{ Env.GITHUB_SERVER_URL }}/{{ Env.GITHUB_REPOSITORY }}/actions/runs/{{ Env.GITHUB_RUN_ID }}
```

**Comment by ericsmalling** [comment]
I'm going to start hacking on a solution for this but am a novice Go coder so be kind in code reviews, plz! :)

**Comment by ericsmalling** [comment]
updated description to use go template for Env var expansion since I see we already have that for other configs

**Comment by halvards** [comment]
If you'd like to use Skaffold to build your ko images, env var support in image labels is already available: https://skaffold.dev/docs/pipeline-stages/builders/ko/#image-labels

**Comment by developer-guy** [comment]
Are you still interested in working on this @ericsmalling? Maybe I can take care of this one if you don't have enough time to look at it.

**Comment by ericsmalling** [comment]
I am, but my schedule this week is slammed. If you have time for it, go right ahead, otherwise I'll pick it up when I can.

**Comment by dio** [comment]
@ericsmalling I think https://github.com/ko-build/ko/compare/main...dio:ko:labels?expand=1 will work. 

I have a question: Do you think we need to allow to set per "build" in "builds"?

**Comment by dio** [comment]
I have a use case for setting image-related information and putting that somehow as a map to a binary (package) build.

For example, I have the following structure:

```
.
├── proj1
│   ├── .ko.yaml
│   ├── Labels.mk
│   ├── Makefile
│   └── cmd
│       └── a
└── proj2
    ├── .ko.yaml
    ├── Labels.mk
    ├── Makefile
    └── cmd
        ├── a
        └── b
```

So for example, between `proj2/cmd/a` `proj2/cmd/b` we need different labels (for name, summary, description, etc as required by https://github.com/redhat-openshift-ecosystem/openshift-preflight). Currently, we manage that separately (inside a `.mk` that can be included in the corresponding `Makefile`), not in the `.ko.yaml`. Do you think we can extend .ko.yaml to accommodate this, by doing one of the following:

1. Add an `images` field, each of its entries that map with each entry in `builds`.
2. Extends build to allow image-related information.

For 1,

```yaml
images:
  id: a
  labels:

builds:
  id: a
```

or for 2,

```yaml

builds:
  id: a
  image:
    labels:
      - name: ok
      - release: v{{ .Env.Tag }}
```

@ericsmalling @imjasonh do you think this makes sense?
