### ISSUE TITLE
Allow using `go test -c` as build command

### ISSUE THREAD

**Issue by k15r** [ko-build/ko#96]
We often use `go test -c` to create binaries that need to run in a cluster to run their tests inside kubernetes. Currently `ko` only supports `go build` as a build command, so for these tests there is currently no way to be applied using `ko`.

I'd be really glad if a flag would allow me to change the build command.

**Comment by jonjohnsonjr** [comment]
@n3wscott had an related idea for a `ko test` command.

How would you want this to work? Similar to `ko apply` but instead of building a main package we create the test binary?

We might be able to do this without a flag, e.g. by checking for [`TestGoFiles`](https://godoc.org/go/build#Package.TestGoFiles) instead of `IsCommand` [here](https://github.com/google/ko/blob/3880b61d2d5f85401f726eda7012157295956360/pkg/build/gobuild.go#L126).

**Comment by k15r** [comment]
i'm fine with any implementation, doesn't need to be a flag, it could also be a new command e.g. `ko test`. If it could figure out automatically which command is required it would allow for some nice scenarios. E.g. that would allow you to install a controller and run its tests with one `ko apply`

**Comment by jonjohnsonjr** [comment]
> E.g. that would allow you to install a controller and run its tests with one ko apply

I think this would be hard to do if there are tests in the same `main` package, but if they were two separate packages, I could imagine something like:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: github.com/google/ko/cmd/ko
---
apiVersion: batch/v1
kind: Job
metadata:
  name: controller-test
spec:
  template:
    spec:
      containers:
      - name: controller-test
        image: github.com/google/ko/cmd/ko/test
      restartPolicy: Never
```

Which would run `github.com/google/ko/cmd/ko` as the controller in a Deployment and `github.com/google/ko/cmd/ko/test` as the test in a Job. This would work with `ko apply`, but then you'd have to look at the Job status to determine if the test succeeds (I guess this isn't too hard?)

WDYT?
